# Generated by Django 3.2.4 on 2021-06-26 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DepartementModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50, verbose_name='')),
                ('mail', models.EmailField(max_length=254, verbose_name='')),
                ('numero', models.CharField(max_length=9, verbose_name='')),
                ('description', models.TextField(verbose_name='')),
            ],
        ),
    ]
