# Generated by Django 3.2.4 on 2021-06-26 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departementmodel',
            options={'verbose_name': 'Departement', 'verbose_name_plural': 'Departements'},
        ),
    ]
